# Site Settings
title: Venil Noronha | Open Source Software Developer
email: hello@venilnoronha.com
description: A blog by Venil Noronha
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://venilnoronha.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Venil Noronha
user_description: Open Source Software Developer
disqus_username: venilnoronha-com

# Social Media
# Remove the item if you don't need it
github_username: venilnoronha
# facebook_username: facebook_username
twitter_username: venilnoronha
instagram_username: venilnoronha
linkedin_username: venilnoronha
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
